[build]
builder = "nixpacks"

[deploy]
releaseCommand = "cd /app && python -m scripts.release"
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --worker-class gevent --workers 4 --worker-connections 100 --timeout 120"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
